### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by michaeltansy** [kollavarsham/ng-table-to-csv#4]
hi could u give more brief explanation on how to use it?

**Comment by floydpink** [comment]
Could you please take a look at the [Getting Started/Usage section](https://github.com/kollavarsham/ng-table-to-csv#getting-started--usage) on the README and see if that helps?

**Comment by michaeltansy** [comment]
Hi @floydpink, i already read the getting started. But the thing is i dont know how to bind the data so that the data can be generate to csv. The getting started only help me to generate a blank csv file

**Comment by floydpink** [comment]
Ah, I see - could you please see if [the live demo/example](http://plnkr.co/Y0r33F) that is given in the [Demo section](https://github.com/kollavarsham/ng-table-to-csv#demo) helps?

**Comment by michaeltansy** [comment]
@floydpink i finally found where the problem. There's an error in the code of this library

> TypeError: tr.is is not a function
>     at ng-table-to-csv.js:54

do u know how to fix this?
