### ISSUE TITLE
Multiple tables on one page

### ISSUE THREAD

**Issue by lgromanowski** [kollavarsham/ng-table-to-csv#9]
Hi,
when I use this module on a page with many tables, like in Plucker example: http://plnkr.co/a4eIbNK0Sg4CZAjrUoFi

Only last export link will create a file with correct data - all other will have data from the last table.

Is there any workaround or maybe quick fix for this issue?

**Comment by MFava91** [comment]
Hi,
@lgromanowski you only need to change the CSV's id, like this:

```html
<a class="btn" title="Export Table" ng-click="csvAnother.generate()" ng-href="{{ csvAnother.link() }}" download="myTable2.txt">
        <i class="glyphicon glyphicon-new-window"></i> Export
      </a>
<table class="table table-bordered" export-csv="csvAnother" 
      separator=";" export-csv-ignore="ignore">
```

Plunker example working: http://plnkr.co/edit/5m7TDS3pPOssVBVvLb8m?p=preview

**Comment by floydpink** [comment]
@lgromanowski - can you please check and confirm if the suggestion from @MFava91 can be considered the resolution for this issue?

Thank you, @MFava91 !

**Comment by lgromanowski** [comment]
Hi,
I can confirm that above plunker's code can be considered as a solution for this issue (could you please add information about it to the readme?). Thank you @MFava91 and @floydpink :)

**Comment by floydpink** [comment]
> could you please add information about it to the readme?

👍  Done!
